### ISSUE TITLE
Is there a way to hide the dot and activeDot?

### ISSUE THREAD

**Issue by karthickvkumar** [fixt/react-native-page-swiper#13]
@cgarvis can we hide the dots and activeDots. Is there a way customize like show and hide that dots

Thanks in advance

**Comment by epeli** [comment]
pager={false}

**Comment by karthickvkumar** [comment]
Thanks @epeli

**Comment by timsuchanek** [comment]
Or use the native way:
https://facebook.github.io/react-native/docs/viewpagerandroid.html#content

**Comment by karthickvkumar** [comment]
Thanks @timsuchanek
