### ISSUE TITLE
This is swallowing events on android for me

### ISSUE THREAD

**Issue by litch** [fixt/react-native-page-swiper#2]
If I have a `TouchableHighlight` within a swiper, it works great with iOS, but on an android emulator or device, the TouchableHighlight never even gets triggered.  I'm not sure why.

**Comment by madwed** [comment]
Thanks for the warning @litch.  I'll take a look at this when I have the chance.

**Comment by madwed** [comment]
Do you have an example project we can look at?

**Comment by cgarvis** [comment]
@litch do you have some example code?

**Comment by epeli** [comment]
I've also found out that this works bit weird on Android. If  something is made touchable with `TouchableOpacity` within the swiper it's really hard to get it to register the touch. It seems that when the swiper is swiped even a pixel the touch gesture gets canceled from the `TouchableOpacity`.

I guess the fix would be to ignore first few pixels before the swiper starts moving.
