### ISSUE TITLE
How to customize the style of dot and activeDot?

### ISSUE THREAD

**Issue by songyouwei** [fixt/react-native-page-swiper#4]

**Comment by cgarvis** [comment]
There is an `activeDot` prop.  You can set this to any CSS color attribute.  Do you need more?

**Comment by sritampatnaik** [comment]
https://gist.github.com/sritampatnaik/ac858f7775a5b47122e8 Your wiper tag should have something like this @songyouwei

**Comment by cgarvis** [comment]
@sritampatnaik that is now how this swiper works.  Only `activeDotColor ` is available to change.
